name: Build RPMs

on:
  workflow_dispatch:

jobs:
  build-fc39:
    strategy:
      matrix:
        runner-size:
          [
            ubuntu-latest,
            jammy-4core,
            jammy-8core,
            jammy-16core,
            jammy-32core,
            jammy-64core,
          ]
        debug: ["true", "false"]
    runs-on: ${{ matrix.runner-size }}
    name: Build Fedora 39 (rawhide) kernel with ACS override patch
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: ./free-space

      - name: Build the Fedora 39 RPMs
        id: build-rpms
        uses: ./fc39-action
        with:
          debug-build: ${{ matrix.debug }}

      - name: Upload the RPMs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${{ steps.build-rpms.outputs.kernel-version }}-fc39-acs-override-rpms
          path: |
            /home/runner/work/_temp/_github_home/rpmbuild/RPMS/x86_64/

  build-fc38:
    strategy:
      matrix:
        runner-size:
          [
            ubuntu-latest,
            jammy-4core,
            jammy-8core,
            jammy-16core,
            jammy-32core,
            jammy-64core,
          ]
        debug: ["true", "false"]
    runs-on: ${{ matrix.runner-size }}
    name: Build Fedora 38 kernel with ACS override patch
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: ./free-space

      - name: Build the Fedora 38 RPMs
        id: build-rpms
        uses: ./fc38-action
        with:
          debug-build: ${{ matrix.debug }}

      - name: Upload the RPMs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${{ steps.build-rpms.outputs.kernel-version }}-fc38-acs-override-rpms
          path: |
            /home/runner/work/_temp/_github_home/rpmbuild/RPMS/x86_64/

  build-fc37:
    strategy:
      matrix:
        runner-size:
          [
            ubuntu-latest,
            jammy-4core,
            jammy-8core,
            jammy-16core,
            jammy-32core,
            jammy-64core,
          ]
        debug: ["true", "false"]
    runs-on: ${{ matrix.runner-size }}
    name: Build Fedora 37 kernel with ACS override patch
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: ./free-space

      - name: Build the Fedora 37 RPMs
        id: build-rpms
        uses: ./fc37-action
        with:
          debug-build: ${{ matrix.debug }}

      - name: Upload the RPMs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${{ steps.build-rpms.outputs.kernel-version }}-fc37-acs-override-rpms
          path: |
            /home/runner/work/_temp/_github_home/rpmbuild/RPMS/x86_64/
